### ISSUE TITLE
This extension is aging - anyone want to keep this cool extension updated?

### ISSUE THREAD

**Issue by StewAlexander-com** [hill/tldr-chrome#10]
Anyone want to keep this app's tl;dr reference file(s) updated with the latest pages available at the master repo?

The master repo (I believe) is located here: https://github.com/tldr-pages/tldr/tree/master/pages

**Comment by StewAlexander-com** [comment]
@hill / @Ljqiii / @pxgamer anyone?

**Comment by hill** [comment]
Will look into this shortly!

**Comment by StewAlexander-com** [comment]
@hill thanks

**Comment by bl-ue** [comment]
@hill Hello 👋🏻!  I'm a @tldr-pages maintainer—are you not maintaining this extension any more?  If you aren't, no problem whatsoever, I'd just like to know for our client list cleanup @ https://github.com/tldr-pages/tldr/issues/4044

**Comment by bl-ue** [comment]
I'm guessing the answer is no, not at all.

**Comment by piraces** [comment]
Hello, @hill @bl-ue I'm currently working in a [fork of this repsitory](https://github.com/piraces/tldr-extension-browser) in order to keep this extension upgraded and publish it for Chrome, Edge and Firefox.

I have just pushed to review the extension in the Chrome and Edge markets, I will inform a tldr-pages mantainer to replace the extension in the "Clients list" If they seem it OK and the extension is published. I am willing to mantain this extension in the future.

The extension is now as it was, with minimal changes to make it cross-browser and upgrade the manifest.

**Comment by owenvoke** [comment]
If @hill is happy with this, I'm happy to update the link in the Clients list. 👍🏻

**Comment by hill** [comment]
@owenvoke - yes totally fine with this. Thanks for taking over @piraces 😊 - appreciate it!

**Comment by StewAlexander-com** [comment]
Please us know when and if the chrome extension is updated, looking forward to using it, thanks!

**Comment by piraces** [comment]
@StewAlexander-com Yes, I'm working on it. I hope the first version gets ready and published soon. I will let you know 😃

**Comment by piraces** [comment]
@StewAlexander-com I have now released an stable version of the extension for [Google Chrome](https://chrome.google.com/webstore/detail/tldr-pages/fcccijijdgmmcjnifgdhcmepnkcdingf), [Firefox](https://addons.mozilla.org/es/firefox/addon/tldr-pages/), [Edge](https://microsoftedge.microsoft.com/addons/detail/tldr-pages/hbplonhehblpcghgkhnjepdbohbpkoak) browsers (repo: https://github.com/piraces/tldr-extension-browser). Please let me know what you think, and if you see somethink wrong 😄 

@owenvoke I updated the [tldr project wiki](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients) adding the client. I dont open a PR to change the README of clients because of this issue (https://github.com/tldr-pages/tldr/issues/5512).

Thank you for the awesome previous work @hill !
I will continue improving the extension 💪

**Comment by StewAlexander-com** [comment]
Well It installs just fine, no idea how to use it, maybe to add a help subheading under the extension in Chrome?

I saw it in the github readme, but it might be nice to have it actually listed somewhere in the extension?

By the way right-clicking any of the commands on my page (that are links) doesn't work:

https://www.stewalexander.com/linux.html

**Comment by piraces** [comment]
@StewAlexander-com Will look into it...

I think there are components that just dont work with the extension (like links or iframes). The idea of add a help subheading under the extension is great!

I will ensure the next version will be more pulish

**Comment by StewAlexander-com** [comment]
Thanks @piraces 

Really appreciate everything you're doing with this …

**Comment by piraces** [comment]
Hi, I have opened a new issue in the fork to continue this conversation and keep track on this: https://github.com/piraces/tldr-extension-browser/issues/3

If you want you can close the issue @hill.

**Comment by StewAlexander-com** [comment]
@piraces - done
